# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/htc/pico/extract-files.sh

# Prebuilt libraries that are needed to build open-source libraries
PRODUCT_COPY_FILES += \
    vendor/htc/pico/proprietary/libcamera.so:obj/lib/libcamera.so \
    vendor/htc/pico/proprietary/libril.so:obj/lib/libril.so


# All the blobs necessary for pico

# Prebuilt Binaries
PRODUCT_COPY_FILES += \
    vendor/htc/pico/proprietary/awb_camera:/system/bin/awb_camera \
    vendor/htc/pico/proprietary/bma150_usr:/system/bin/bma150_usr \
    vendor/htc/pico/proprietary/btld:/system/bin/btld \
    vendor/htc/pico/proprietary/htc_ebdlogd:/system/bin/htc_ebdlogd \
    vendor/htc/pico/proprietary/ip:/system/bin/ip \
    vendor/htc/pico/proprietary/ipd:/system/bin/ipd \
    vendor/htc/pico/proprietary/logcat2:/system/bin/logcat2 \
    vendor/htc/pico/proprietary/lsc_camera:/system/bin/lsc_camera \
    vendor/htc/pico/proprietary/netsharing:/system/bin/netsharing \
    vendor/htc/pico/proprietary/rild:/system/bin/rild \
    vendor/htc/pico/proprietary/ser2net:/system/bin/ser2net \
    vendor/htc/pico/proprietary/snd8k:/system/bin/snd8k \
    vendor/htc/pico/proprietary/tc:/system/bin/tc \
    vendor/htc/pico/proprietary/wireless_modem:/system/xbin/wireless_modem \

# Prebuilt Libraries
PRODUCT_COPY_FILES += \
    vendor/htc/pico/proprietary/gps.pico.so:/system/lib/hw/gps.pico.so \
    vendor/htc/pico/proprietary/libEGL_adreno200.so:/system/lib/egl/libEGL_adreno200.so \
    vendor/htc/pico/proprietary/libGLESv1_CM_adreno200.so:/system/lib/egl/libGLESv1_CM_adreno200.so \
    vendor/htc/pico/proprietary/libGLESv2_adreno200.so:/system/lib/egl/libGLESv2_adreno200.so \
    vendor/htc/pico/proprietary/libq3dtools_adreno200.so:/system/lib/egl/libq3dtools_adreno200.so \
    vendor/htc/pico/proprietary/libaudioeq.so:/system/lib/libaudioeq.so \
    vendor/htc/pico/proprietary/libcamera.so:/system/lib/libcamera.so \
    vendor/htc/pico/proprietary/libgsl.so:/system/lib/libgsl.so \
    vendor/htc/pico/proprietary/libhtc_acoustic.so:/system/lib/libhtc_acoustic.so \
    vendor/htc/pico/proprietary/libril.so:/system/lib/libril.so \
    vendor/htc/pico/proprietary/libhtc_ril.so:/system/lib/libhtc_ril.so \
    vendor/htc/pico/proprietary/libhtc_ril_switch.so:/system/lib/libhtc_ril_switch.so \
    vendor/htc/pico/proprietary/libmm-adspsvc.so:/system/bin/libmm-adspsvc.so \
    vendor/htc/pico/proprietary/libmmipl.so:/system/lib/libmmipl.so \
    vendor/htc/pico/proprietary/libmmjpeg.so:/system/lib/libmmjpeg.so \
    vendor/htc/pico/proprietary/liboemcamera.so:/system/lib/liboemcamera.so \
    vendor/htc/pico/proprietary/libchromatix_mt9t013_default_video.so:/system/lib/libchromatix_mt9t013_default_video.so \
    vendor/htc/pico/proprietary/libchromatix_mt9t013_preview.so:/system/lib/libchromatix_mt9t013_preview.so \
    vendor/htc/pico/proprietary/libmm-omxcore.so:/system/lib/libmm-omxcore.so \
    vendor/htc/pico/proprietary/libOmxH264Dec.so:/system/lib/libOmxH264Dec.so \
    vendor/htc/pico/proprietary/libOmxMpeg4Dec.so:/system/lib/libOmxMpeg4Dec.so \
    vendor/htc/pico/proprietary/libOmxVidEnc.so:/system/lib/libOmxVidEnc.so \
    vendor/htc/pico/proprietary/libwebkitaccel.so:/system/lib/libwebkitaccel.so \
    vendor/htc/pico/proprietary/libgsl.so:/system/lib/libgsl.so \
    vendor/htc/pico/proprietary/libOlaEngine.so:/system/lib/libOlaEngine.so \
    vendor/htc/pico/proprietary/libwsp.so:/system/lib/libwsp.so \
    vendor/htc/pico/proprietary/libwsp_jni.so:/system/lib/libwsp_jni.so \
    vendor/htc/mecha/proprietary/libreference-cdma-sms.so:/system/lib/libreference-cdma-sms.so \

# Misc. Props
PRODUCT_COPY_FILES += \    
   vendor/htc/pico/proprietary/AudioBTID.csv:/system/etc/AudioBTID.csv \
   vendor/htc/pico/proprietary/AudioFilter.csv:/system/etc/AudioFilter.csv \
   vendor/htc/pico/proprietary/AudioPara4.csv:/system/etc/AudioPara4.csv \
   vendor/htc/pico/proprietary/AudioPara4_WB.csv:/system/etc/AudioPara4_WB.csv \
   vendor/htc/pico/proprietary/AudioPreProcess.csv:/system/bin/AudioPreProcess.csv \

